README.md
api/src/test/scala/com/github/andyglow/jsonschema/AsValueSpec.scala
api/src/test/scala/com/github/andyglow/jsonschema/SchemaMacroSpec.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsValue.scala
core/src/main/scala/json/Schema.scala
macros/src/main/scala/com/github/andyglow/jsonschema/SchemaMacro.scala

As in subject. Also updated readme.

Add support for Char and case classes extending sealed trait

---

README.md

Small documentation improvements

add example of SBT dependency, fix schema as value example

---

api/src/test/scala/com/github/andyglow/jsonschema/AsDraft04Spec.scala
api/src/test/scala/com/github/andyglow/jsonschema/CRLFSourceSpec.scala
api/src/test/scala/com/github/andyglow/jsonschema/SchemaMacroSpec.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsDraftSupport.scala
core/src/main/scala/json/Schema.scala
core/src/main/scala/json/schema/Predef.scala
macros/src/main/scala/com/github/andyglow/jsonschema/SchemaMacro.scala
modules/cats/src/main/scala/com/github/andyglow/jsonschema/CatsSupport.scala
modules/cats/src/test/scala/com/github/andyglow/jsonschema/CatsSupportSpec.scala
modules/parser/src/main/scala/com/github/andyglow/jsonschema/ParseJsonSchema.scala

support sealed object hierarchies types (enums) as map keys

---

core/src/main/scala/json/Schema.scala
core/src/main/scala/json/schema/Predef.scala
macros/src/main/scala/com/github/andyglow/jsonschema/SchemaMacro.scala
modules/cats/src/main/scala/com/github/andyglow/jsonschema/CatsSupport.scala
modules/enumeratum/src/main/scala/com/github/andyglow/jsonschema/EnumeratumSupport.scala
modules/enumeratum/src/test/scala/com/github/andyglow/jsonschema/EnumeratumSupportSpec.scala

Feature Request: support Map[EnumEntry, V] of enumeratum's EnumEntry

---

README.md
api/src/main/scala/json/Json.scala
api/src/test/scala/com/example/unrelated/CommentsMain.scala
api/src/test/scala/com/example/unrelated/models.scala
api/src/test/scala/com/github/andyglow/jsonschema/DocumentationSpec.scala
api/src/test/scala/com/github/andyglow/jsonschema/SchemaMacroSpec.scala
build.sbt
core/src/main/scala/json/Schema.scala
core/src/main/scala/json/schema/description.scala
core/src/main/scala/json/schema/title.scala
macros/src/main/scala/com/github/andyglow/jsonschema/SchemaMacro.scala

ralated to `Add scaladoc as description in the schema` #18

allow configuring descriptions and titles using (annotations, scaladoc, config)

---

api/src/test/scala/com/github/andyglow/jsonschema/DocumentationSpec.scala
build.sbt
core/src/main/scala/com/github/andyglow/json/Escaped.scala
core/src/main/scala/com/github/andyglow/json/JsonFormatter.scala
core/src/test/scala/com/github/andyglow/json/JsonFormatterSpec.scala
modules/circe-json/src/test/scala/com/github/andyglow/jsonschema/AsCirceSpec.scala
modules/json4s-json/src/test/scala/com/github/andyglow/jsonschema/AsJson4sSpec.scala
modules/play-json/src/test/scala/com/github/andyglow/jsonschema/AsPlaySpec.scala
modules/refined/src/test/scala/com.github.andyglow.jsonschema.refined/RefinedEscapedSpec.scala
modules/spray-json/src/test/scala/com/github/andyglow/jsonschema/AsSpraySpec.scala
modules/u-json/src/test/scala/com/github/andyglow/jsonschema/AsUSpec.scala

json strings need to be escaped

---

.gitignore
api/src/test/scala/com/github/andyglow/jsonschema/AsDraft04Spec.scala
api/src/test/scala/com/github/andyglow/jsonschema/DefinitionsSpec.scala
api/src/test/scala/com/github/andyglow/jsonschema/SchemaMacroSpec.scala
build.sbt
core/src/main/scala/com/github/andyglow/jsonschema/AsDraftSupport.scala
core/src/main/scala/json/Schema.scala
macros/src/main/scala/com/github/andyglow/jsonschema/SchemaMacro.scala
project/build.properties
version.sbt

- improve value-class handling
- upgrade sbt to 1.4.1

Improve Value Class Handling

---

CHANGELOG.md
README.md
api/src/test/scala/com/github/andyglow/jsonschema/SchemaMacroSpec.scala
macros/src/main/scala/com/github/andyglow/jsonschema/UEnums.scala

Add scala-enumeration support

---

.travis.yml
api/src/test/scala/com/github/andyglow/jsonschema/AsDraft04Spec.scala
api/src/test/scala/com/github/andyglow/jsonschema/AsDraft06Spec.scala
api/src/test/scala/com/github/andyglow/jsonschema/AsDraft07Spec.scala
api/src/test/scala/com/github/andyglow/jsonschema/CRLFSourceSpec.scala
api/src/test/scala/com/github/andyglow/jsonschema/DefinitionsSpec.scala
api/src/test/scala/com/github/andyglow/jsonschema/GenericSchemaMacroSpec.scala
api/src/test/scala/com/github/andyglow/jsonschema/RecursiveTypesSpec.scala
api/src/test/scala/com/github/andyglow/jsonschema/SchemaMacroSpec.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsDraft06.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsDraft07.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsDraftSupport.scala
core/src/main/scala/json/Schema.scala
core/src/main/scala/json/schema/Predef.scala
macros/src/main/scala/com/github/andyglow/jsonschema/Macroses.scala
macros/src/main/scala/com/github/andyglow/jsonschema/SchemaTypes.scala
macros/src/main/scala/com/github/andyglow/jsonschema/UCommons.scala
macros/src/main/scala/com/github/andyglow/jsonschema/UImplicits.scala
macros/src/main/scala/com/github/andyglow/jsonschema/URecursiveTypes.scala
modules/cats/src/test/scala-2.12-/com/github/andyglow/jsonschema/ScalaVersionSpecificCatsSupportSpec.scala
modules/cats/src/test/scala-2.13+/com/github/andyglow/jsonschema/ScalaVersionSpecificCatsSupportSpec.scala
modules/cats/src/test/scala/com/github/andyglow/jsonschema/CatsSupportSpec.scala
modules/enumeratum/src/test/scala/com/github/andyglow/jsonschema/EnumeratumSupportSpec.scala
modules/joda-time/src/test/scala/com/github/andyglow/jsonschema/JodaTimeSupportSpec.scala
modules/parser/src/test/scala/com/github/andyglow/jsonschema/ParseJsonSchemaSpec.scala
modules/refined/src/main/scala/com/github/andyglow/jsonschema/refined/AST.scala
modules/refined/src/test/scala/com.github.andyglow.jsonschema.refined/RefinedEscapedSpec.scala
modules/u-json/src/test/scala/com/github/andyglow/jsonschema/AsUSpec.scala
project/plugins.sbt

- closes #90 
- may resolve confusion in #80

Definitions remastered

---

modules/refined/src/main/scala/com/github/andyglow/jsonschema/refined/Extractors.scala
modules/refined/src/test/scala/com.github.andyglow.jsonschema.refined/RefinedAliasedSpec.scala

add support for aliased refined types

---

modules/refined/src/main/scala/com/github/andyglow/jsonschema/refined/AST.scala
modules/refined/src/test/scala/com.github.andyglow.jsonschema.refined/RefinedBooleanSpec.scala
modules/refined/src/test/scala/com.github.andyglow.jsonschema.refined/RefinedNumbersSpec.scala

Force `integer` for Refined Int/Integer

---

macros/src/main/scala/com/github/andyglow/jsonschema/UTypeAnnotations.scala
modules/cats/src/main/scala/com/github/andyglow/jsonschema/CatsSupport.scala
modules/cats/src/test/scala/com/github/andyglow/jsonschema/CatsSupportSpec.scala

improve handling of Cats's NonEmptySet

---

core/src/main/scala/com/github/andyglow/json/JsonFormatter.scala
core/src/main/scala/com/github/andyglow/json/Value.scala
core/src/test/scala/com/github/andyglow/json/JsonFormatterSpec.scala

allow sorted output for `JsonFormatter`

---

api/src/test/scala/com/github/andyglow/jsonschema/DiscriminatorSpec.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsDraft06.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsDraft07.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsDraftSupport.scala
macros/src/main/scala/com/github/andyglow/jsonschema/USumTypes.scala

Fix Discriminator/DiscriminatorKey Logic for Objets that come as Definition

---

README.md
api/src/test/scala/com/github/andyglow/jsonschema/AsDraft04Spec.scala
api/src/test/scala/com/github/andyglow/jsonschema/DefinitionsSpec.scala
api/src/test/scala/com/github/andyglow/jsonschema/RWSpec.scala
core/src/main/scala/com/github/andyglow/json/Value.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsDraftSupport.scala
core/src/main/scala/json/Schema.scala
core/src/main/scala/json/schema/readOnly.scala
core/src/main/scala/json/schema/writeOnly.scala
macros/src/main/scala/com/github/andyglow/jsonschema/SchemaTypes.scala
macros/src/main/scala/com/github/andyglow/jsonschema/UCommons.scala
macros/src/main/scala/com/github/andyglow/jsonschema/UProductTypes.scala

add support for readOnly/writeOnly validations

---

CHANGELOG.md
api/src/test/scala/com/github/andyglow/jsonschema/AsDraft04Spec.scala
api/src/test/scala/com/github/andyglow/jsonschema/AsDraft06Spec.scala
api/src/test/scala/com/github/andyglow/jsonschema/AsDraft07Spec.scala
api/src/test/scala/com/github/andyglow/jsonschema/AsDraft09Spec.scala
api/src/test/scala/com/github/andyglow/jsonschema/JsonMatchers.scala
build.sbt
core/src/main/scala-2.11/com/github/andyglow/scalamigration.scala
core/src/main/scala-2.12/com/github/andyglow/scalamigration.scala
core/src/main/scala-2.13/com/github/andyglow/scalamigration.scala
core/src/main/scala/com/github/andyglow/json/Value.scala
core/src/main/scala/com/github/andyglow/json/comparison.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsDraft04.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsDraft06.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsDraft09.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsDraftSupport.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsRaw.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsValueBuilder.scala
core/src/main/scala/com/github/andyglow/jsonschema/Constants.scala
core/src/main/scala/com/github/andyglow/jsonschema/Post09.scala
core/src/main/scala/com/github/andyglow/jsonschema/Pre09.scala
core/src/main/scala/json/Schema.scala
core/src/main/scala/json/schema/Predef.scala
core/src/main/scala/json/schema/Version.scala
core/src/test/scala/com/github/andyglow/json/DiffSpec.scala
modules/joda-time/src/main/scala/com/github/andyglow/jsonschema/JodaTimeSupport.scala
project/ScalaVer.scala

implement 2019-09

---

api/src/test/scala/com/github/andyglow/jsonschema/DocumentationSpec.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsDraft04.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsDraft06.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsDraft07.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsDraft09.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsDraftSupport.scala

move description/title from root level to object (aka root AND definition) level

---

api/src/test/scala/com/github/andyglow/jsonschema/RWSpec.scala
build.sbt
core/src/main/scala/com/github/andyglow/jsonschema/AsDraftSupport.scala
core/src/main/scala/json/Schema.scala
macros/src/main/scala/com/github/andyglow/jsonschema/Macroses.scala
macros/src/main/scala/com/github/andyglow/jsonschema/SchemaTypes.scala
macros/src/main/scala/com/github/andyglow/jsonschema/UCommons.scala
macros/src/main/scala/com/github/andyglow/jsonschema/UProductTypes.scala
macros/src/main/scala/com/github/andyglow/jsonschema/USumTypes.scala
modules/derived/src/main/scala/json/schema/derived/DerivedSchema.scala
modules/derived/src/test/scala/json/schema/derived/DerivedSchemaSpec.scala
project/CompilerOptions.scala
project/ScalaVer.scala

allow implicit schema derivation

---

build.sbt

update scaladoc to 0.0.13

---

build.sbt

update scaladoc to 0.0.14

---

api/src/test/scala/com/github/andyglow/jsonschema/SchemaMacroSpec.scala
macros/src/main/scala/com/github/andyglow/jsonschema/UDictionaries.scala

allow Map key to be specified using value class

---

core/src/main/scala/json/schema/Predef.scala

add zoned date time support

---

api/src/test/scala/com/github/andyglow/jsonschema/DefinitionsSpec.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsDraftSupport.scala
core/src/main/scala/json/Schema.scala

fix issue for Def(ValueClass) with disappeared validations

---

README.md
api/src/test/scala/com/github/andyglow/jsonschema/AsDraft04Spec.scala
api/src/test/scala/com/github/andyglow/jsonschema/AsDraft06Spec.scala
api/src/test/scala/com/github/andyglow/jsonschema/AsDraft07Spec.scala
api/src/test/scala/com/github/andyglow/jsonschema/AsDraft09Spec.scala
api/src/test/scala/com/github/andyglow/jsonschema/EnumSpec.scala
api/src/test/scala/com/github/andyglow/jsonschema/Example.scala
api/src/test/scala/com/github/andyglow/jsonschema/SchemaMacroSpec.scala
api/src/test/scala/com/github/andyglow/jsonschema/SumTypeModels.scala
api/src/test/scala/com/github/andyglow/jsonschema/SumTypeWithEnumsSpec.scala
api/src/test/scala/com/github/andyglow/jsonschema/SumeTypeWithConstantsSpec.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsDraftSupport.scala
core/src/main/scala/json/Schema.scala
core/src/main/scala/json/schema/Flag.scala
macros/src/main/scala/com/github/andyglow/jsonschema/Macroses.scala
macros/src/main/scala/com/github/andyglow/jsonschema/SchemaTypes.scala
macros/src/main/scala/com/github/andyglow/jsonschema/UCommons.scala
macros/src/main/scala/com/github/andyglow/jsonschema/UEnums.scala
macros/src/main/scala/com/github/andyglow/jsonschema/UFlags.scala
macros/src/main/scala/com/github/andyglow/jsonschema/UImplicits.scala
macros/src/main/scala/com/github/andyglow/jsonschema/USumTypes.scala

this interfere with #230 
as well as #190

introduce documentable sum-types with toggle that turns enums into oneofs

---

api/src/test/scala/com/github/andyglow/jsonschema/SchemaMacroSpec.scala
core/src/main/scala/json/Schema.scala

fix the issue with `value-class` being a part of a `oneof`

---

core/src/main/scala/json/Schema.scala
core/src/test/scala/json/SchemaSpec.scala

ensure extra got copied over whenever `copy` method is used

---

api/src/test/scala/com/github/andyglow/jsonschema/SchemaMacroSpec.scala
api/src/test/scala/com/github/andyglow/jsonschema/SumTypeWithConstantsSpec.scala
api/src/test/scala/com/github/andyglow/jsonschema/SumTypeWithEnumsSpec.scala
build.sbt
core/src/main/scala-2.11/com/github/andyglow/scalamigration.scala
core/src/main/scala-2.12/com/github/andyglow/scalamigration.scala
core/src/main/scala-2.13/com/github/andyglow/scalamigration.scala
core/src/main/scala/com/github/andyglow/json/Value.scala
macros/src/main/scala/com/github/andyglow/jsonschema/UDictionaries.scala
modules/circe-json/src/main/scala/com/github/andyglow/jsonschema/AsCirce.scala
modules/json4s-json/src/test/scala/com/github/andyglow/jsonschema/AsJson4sSpec.scala
modules/spray-json/src/test/scala/com/github/andyglow/jsonschema/AsSpraySpec.scala
modules/u-json/src/test/scala/com/github/andyglow/jsonschema/AsUSpec.scala
project/ScalaVer.scala
project/build.properties

- cleanup warnings
- upgrade sbt to 1.6.2
- make docs participate in 2.13 builds only

Housekeeping

---

api/src/test/scala/com/github/andyglow/jsonschema/SchemaMacroSpec.scala
api/src/test/scala/com/github/andyglow/jsonschema/SchemaMatchers.scala
core/src/main/scala-2.11/com/github/andyglow/scalamigration.scala
core/src/main/scala/com/github/andyglow/jsonschema/AsDraftSupport.scala
core/src/main/scala/com/github/andyglow/jsonschema/SchemaEquality.scala
core/src/main/scala/json/Schema.scala
core/src/test/scala/com/github/andyglow/jsonschema/SchemaEqualitySpec.scala
macros/src/main/scala/com/github/andyglow/jsonschema/SchemaTypes.scala
macros/src/main/scala/com/github/andyglow/jsonschema/UProductTypes.scala
modules/parser/src/main/scala/com/github/andyglow/jsonschema/ParseJsonSchema.scala

Preserve Field Order
